class Set < Object
include Enumerable
include Kernel
def self.[](*args);end
def self.[](*args);end
def &(enum);end
def +(enum);end
def -(enum);end
def ^(enum);end
def |(enum);end
def <<(o);end
def empty?();end
def length();end
def size();end
def each(&block);end
def to_a();end
def member?(o);end
def replace(enum);end
def clear();end
def delete(o);end
def collect!();end
def map!();end
def select!(&block);end
def keep_if();end
def delete_if();end
def reject!(&block);end
def flatten();end
def flatten!();end
def merge(enum);end
def union(enum);end
def add(o);end
def pretty_print(pp);end
def to_set(*args);end
def superset?(set);end
def proper_superset?(set);end
def subset?(set);end
def proper_subset?(set);end
def intersect?(set);end
def disjoint?(set);end
def add?(o);end
def delete?(o);end
def subtract(enum);end
def difference(enum);end
def intersection(enum);end
def classify();end
def divide(&func);end
def pretty_print_cycle(pp);end
end
class SortedSet < Set
include Enumerable
include Kernel
def self.[](*args);end
def self.setup();end
def self.[](*args);end
def self.setup();end
end
