---
inherit_from: .rubocop_todo.yml

# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
AllCops:
  NewCops: enable
  Exclude:
    - "spec/fixtures/invalid_byte.rb"
    - "spec/fixtures/invalid_node_comment.rb"
    - "spec/fixtures/invalid_utf8.rb"
  TargetRubyVersion: 3.0

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/MethodLength:
  Max: 25

plugins:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-yard
