module Open3
def popen3(*args);end
def popen2(*args);end
def popen2e(*args);end
def capture3(*args);end
def capture2(*args);end
def capture2e(*args);end
def pipeline_rw(*args);end
def pipeline_r(*args);end
def pipeline_w(*args);end
def pipeline_start(*args);end
def pipeline(*args);end
def self.popen3(*args);end
def self.popen2(*args);end
def self.popen2e(*args);end
def self.capture3(*args);end
def self.capture2(*args);end
def self.capture2e(*args);end
def self.pipeline_rw(*args);end
def self.pipeline_r(*args);end
def self.pipeline_w(*args);end
def self.pipeline_start(*args);end
def self.pipeline(*args);end
end
