# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with rspec.
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Typecheck

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  solargraph_typed:
    name: Solargraph / strong

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: false
    - name: Install gems
      run: |
        bundle install
        bundle update rbs # use latest available for this Ruby version
    - name: Install gem types
      run: bundle exec rbs collection install
    - name: Typecheck self
      run: SOLARGRAPH_ASSERTS=on bundle exec solargraph typecheck --level strong
